@ECHO OFF
ECHO Deleting bin folders...
FOR /F "tokens=*" %%G IN ('DIR /B /AD /S bin') DO RMDIR /S /Q "%%G" > NUL 2> NUL
ECHO Deleting obj folders...
FOR /F "tokens=*" %%G IN ('DIR /B /AD /S obj') DO RMDIR /S /Q "%%G" > NUL 2> NUL
ECHO Deleting generated packages...
FOR /F "tokens=*" %%G IN ('DIR /B LocalPackageRepository') DO DEL /Q "%%G" > NUL 2> NUL
ECHO Deleting generated packages from local cache...
FOR /F "tokens=*" %%G IN ('DIR /B /AD .') DO RMDIR /S /Q packages\%%G > NUL 2> NUL
